name: CI

on:
  push:
    branches:
    - staging
    - trying

jobs:
  build:
    name: build all
    timeout-minutes: 360
    runs-on: ubuntu-latest

    strategy:
      matrix:
        nixpkgs: [ lockfile ]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Nix
      uses: cachix/install-nix-action@v6

    - name: nix-build (for ${{ matrix.nixpkgs }})
      env:
        NIXPKGS_CHANNEL: ${{ matrix.nixpkgs }}
      run: nix-build --no-link --arg nixpkgs "channel:$NIXPKGS_CHANNEL"
